In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [2]:
df = pd.read_csv('Churn_Modelling.csv')
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
data=df.drop(['RowNumber','CustomerId','Surname'],axis=1)
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0

In [5]:
from sklearn.preprocessing import OneHotEncoder
ohe_geo=OneHotEncoder()
geo_encoder=ohe_geo.fit_transform(data[['Geography']]).toarray()
geo_encoder

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [6]:
ohe_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [7]:
geo_encoded_df=pd.DataFrame(geo_encoder,columns=ohe_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [8]:
data=pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [9]:
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('ohe_geo.pkl','wb') as file:
    pickle.dump(ohe_geo,file)

In [10]:
X=data.drop('Exited',axis=1)
y=data['Exited']

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [11]:
X_train_scaled

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [12]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

# ANN Implimentation

In [13]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

WARNING:tensorflow:From d:\DL(ANN) Project\annvenv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [14]:
(X_train.shape[1],)

(12,)

In [15]:
model=Sequential([
    Dense(72,activation='relu',input_shape=(X_train.shape[1],)), ## HL1 Connected wwith input layer
    Dense(42,activation='relu'), ## HL2
    Dense(1,activation='sigmoid')  ## output layer
]

)

WARNING:tensorflow:From d:\DL(ANN) Project\annvenv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 72)                936

 dense_1 (Dense)             (None, 42)                3066

 dense_2 (Dense)             (None, 1)                 43

=================================================================
Total params: 4045 (15.80 KB)
Trainable params: 4045 (15.80 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [17]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss=tensorflow.keras.losses.BinaryCrossentropy()
loss

In [18]:
model.compile(optimizer=opt,loss="binary_crossentropy",metrics=['accuracy'])

In [19]:
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard

log_dir="logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [20]:
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=15,restore_best_weights=True)

In [21]:
history=model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=130,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/130
WARNING:tensorflow:From d:\DL(ANN) Project\annvenv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From d:\DL(ANN) Project\annvenv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 1s 3ms/step - loss: 213.9287 - accuracy: 0.6743 - val_loss: 28.6660 - val_accuracy: 0.5365
Epoch 2/130
250/250 [==============================] - 0s 2ms/step - loss: 33.4807 - accuracy: 0.6744 - val_loss: 8.5016 - val_accuracy: 0.8025
Epoch 3/130
250/250 [==============================] - 0s 2ms/step - loss: 10.2182 - accuracy: 0.6820 - val_loss: 9.3213 - val_accuracy: 0.8035
Epoch 4/130
250/250 [==============================] - 0s 2ms/step - loss: 4.4853 - accuracy: 0.6777 - val_loss: 2.3139 - val_accuracy: 0.7960
Epoch 5/130
250/250 [==============================] - 0s 2ms/step - loss: 2.1152 - accuracy: 0.6965 - val_loss: 3.3813 - val_accuracy: 0.8035
Epoch 6/130
250/250 [==============================] - 0s 2ms/step - loss: 1.1277 - accuracy: 0.7175 - val_loss: 0.5726 - val_accuracy: 0.7835
Epoch 7/130
250/250 [==============================] - 0s 2ms/step - loss: 0.5813 - accuracy: 0.7638 - val_loss: 0.5160 - val_accuracy: 0.8035
Epoch 8/130
250/250 [==============================] - 0s 2ms/step - loss: 0.5379 - accuracy: 0.7861 - val_loss: 0.4969 - val_accuracy: 0.8035
Epoch 9/130
250/250 [==============================] - 0s 2ms/step - loss: 0.5203 - accuracy: 0.7908 - val_loss: 0.5142 - val_accuracy: 0.8035
Epoch 10/130
250/250 [==============================] - 0s 2ms/step - loss: 0.5103 - accuracy: 0.7934 - val_loss: 0.4939 - val_accuracy: 0.8035
Epoch 11/130
250/250 [==============================] - 0s 2ms/step - loss: 0.5068 - accuracy: 0.7944 - val_loss: 0.4952 - val_accuracy: 0.8035
Epoch 12/130
250/250 [==============================] - 0s 2ms/step - loss: 0.5048 - accuracy: 0.7944 - val_loss: 0.4917 - val_accuracy: 0.8040
Epoch 13/130
250/250 [==============================] - 0s 2ms/step - loss: 0.5045 - accuracy: 0.7944 - val_loss: 0.4923 - val_accuracy: 0.8035
Epoch 14/130
250/250 [==============================] - 0s 2ms/step - loss: 0.5062 - accuracy: 0.7943 - val_loss: 0.4917 - val_accuracy: 0.8035
Epoch 15/130
250/250 [==============================] - 0s 2ms/step - loss: 0.5057 - accuracy: 0.7937 - val_loss: 0.4970 - val_accuracy: 0.8035
Epoch 16/130
250/250 [==============================] - 0s 2ms/step - loss: 0.5077 - accuracy: 0.7945 - val_loss: 0.4901 - val_accuracy: 0.8035
Epoch 17/130
250/250 [==============================] - 0s 2ms/step - loss: 0.5038 - accuracy: 0.7945 - val_loss: 0.4947 - val_accuracy: 0.8035
Epoch 18/130
250/250 [==============================] - 0s 2ms/step - loss: 0.5075 - accuracy: 0.7945 - val_loss: 0.4903 - val_accuracy: 0.8035
Epoch 19/130
250/250 [==============================] - 0s 2ms/step - loss: 0.5048 - accuracy: 0.7944 - val_loss: 0.4980 - val_accuracy: 0.8035
Epoch 20/130
250/250 [==============================] - 0s 2ms/step - loss: 0.5084 - accuracy: 0.7944 - val_loss: 0.4961 - val_accuracy: 0.8035
Epoch 21/130
250/250 [==============================] - 0s 2ms/step - loss: 0.5088 - accuracy: 0.7945 - val_loss: 0.4955 - val_accuracy: 0.8030
Epoch 22/130
250/250 [==============================] - 0s 2ms/step - loss: 0.5095 - accuracy: 0.7939 - val_loss: 0.4955 - val_accuracy: 0.8035
Epoch 23/130
250/250 [==============================] - 0s 2ms/step - loss: 0.5083 - accuracy: 0.7945 - val_loss: 0.4957 - val_accuracy: 0.8035
Epoch 24/130
250/250 [==============================] - 0s 2ms/step - loss: 0.5080 - accuracy: 0.7945 - val_loss: 0.4952 - val_accuracy: 0.8035
Epoch 25/130
250/250 [==============================] - 0s 2ms/step - loss: 0.5077 - accuracy: 0.7945 - val_loss: 0.4956 - val_accuracy: 0.8035
Epoch 26/130
250/250 [==============================] - 0s 2ms/step - loss: 0.5077 - accuracy: 0.7945 - val_loss: 0.4952 - val_accuracy: 0.8035
Epoch 27/130
250/250 [==============================] - 0s 2ms/step - loss: 0.5079 - accuracy: 0.7945 - val_loss: 0.4952 - val_accuracy: 0.8035
Epoch 28/130
250/250 [==============================] - 0s 2ms/step - loss: 0.5072 - accuracy: 0.7945 - val_loss: 0.4951 - val_accuracy: 0.8035
Epoch 29/130
250/250 [==============================] - 0s 2ms/step - loss: 0.5076 - accuracy: 0.7945 - val_loss: 0.4949 - val_accuracy: 0.8035
Epoch 30/130
250/250 [==============================] - 0s 2ms/step - loss: 0.5077 - accuracy: 0.7945 - val_loss: 0.4950 - val_accuracy: 0.8035
Epoch 31/130
250/250 [==============================] - 0s 2ms/step - loss: 0.5076 - accuracy: 0.7945 - val_loss: 0.4947 - val_accuracy: 0.8035

In [25]:
model.save("model.keras")

In [23]:
%load_ext tensorboard

In [27]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 35200), started 2 days, 5:52:32 ago. (Use '!kill 35200' to kill it.)